### ISSUE TITLE
Opposite-direction inflow from outflow boundary in precursor restart with OpenFAST turbine

### ISSUE THREAD

**Issue by jfrederik-nrel** [Exawind/amr-wind#1341] opened 2024-11-11 17:24 UTC
## Bug description
When restarting a precursor simulation with an OpenFAST turbine, the flow seems to become unstable near the eastern boundary of the flow field (inflow comes from western boundary). In the precursor simulation without turbines, the flow looks normal and has no such issues. I've also tried rerunning the precursor: the original precursor had a bigger flow field (5x5km instead of 5x2.5) and had a 30 degree wind direction offset. The issue between both cases seems identical, though, and also happens after about the same simulation time (starts looking off after 600s of simulation time, crashes after about 900s). 

I also initially ran these simulations in an older version of AMR-Wind (v2.0), but updated to the latest version (v3.2) last week and saw no significant differences between versions. See details for the latest run below, as well as screenshots of the flow and the restart input file used.

## Steps to reproduce

1. Compiler used
   - [ ] GCC
   - [ ] LLVM
   - [x] oneapi (Intel)
   - [ ] nvcc (NVIDIA)
   - [ ] rocm (AMD)
   - [ ] with MPI
   - [ ] other:
2. Operating system
   - [x] Linux
   - [ ] OSX
   - [ ] Windows
   - [ ] other (do tell ;)):
3. Hardware:
   - [x] CPU
   - [ ] GPU
4. Machine details ():
Kestrel NREL HPC
```
source /nopt/nrel/apps/cpu_stack/env_cpe23.sh
module load PrgEnv-intel
ml intel-oneapi-tbb/2021.11.0-intel
ml intel-oneapi-mkl/2024.0.0-intel
ml netcdf/4.9.2-intel-oneapi-mpi-intel
```
5. Input file attachments
[8ms_z15_turbine.txt](https://github.com/user-attachments/files/17707938/8ms_z15_turbine.txt)

6. Error (paste or attach):
This is the error given, but I am pretty sure it is just a consequence of what is really going wrong, not the reason. 
```
CFL: 1.29592e+14 (conv: 1.29592e+14 diff: 0 src: 249.19 )
WARNING: fixed_dt does not satisfy CFL condition.
Max. CFL: 0.95 => dt: 3.66536e-16; dt_inp: 0.05
 Warning: SkewedWakeCorrection encountered a large value of chi (90.097 deg), so the yaw
 correction will be limited. This warning will not be repeated though the condition may persist.
 See the AD15 chi output channels, and consider turning off the Pitt/Peters skew model (set
 SkewMod=1) if this condition persists.

 The BEM solution is being turned off due to low TSR.  (TSR = -1.61671E-03). This warning will not
 be repeated though the condition may persist. (See GeomPhi output channel.)
terminate called after throwing an instance of 'std::runtime_error'
  what():  FastIface: Error calling OpenFAST function: 
FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:AD_CalcOutput:RotCalcOutput:BEMT_CalcOutput(node 4, blade 1):UA_CalcOutput:Mach number exceeds 1.0. Equations cannot be evaluated.
srun: error: x1005c0s4b0n0: task 46: Aborted (core dumped)
srun: Terminating StepId=6017728.0
slurmstepd: error: *** STEP 6017728.0 ON x1005c0s4b0n0 CANCELLED AT 2024-11-10T00:15:14 ***
srun: error: x1005c0s5b1n0: task 206: Terminated
srun: error: x1005c0s4b0n1: tasks 107,121: Terminated
srun: error: x1005c1s1b0n0: tasks 374,377,379: Terminated
srun: error: x1005c0s7b1n0: tasks 282,288,339: Terminated
srun: error: x1005c1s6b0n1: tasks 460-551: Terminated
srun: error: x1005c2s1b0n1: tasks 552-643: Terminated
srun: error: x1005c2s3b0n1: tasks 644-735: Terminated
srun: error: x1005c1s1b0n0: tasks 368-373,375-376,378,380-459: Terminated
srun: error: x1005c0s7b1n0: tasks 276-281,283-287,289-338,340-367: Terminated
srun: error: x1005c0s4b0n0: tasks 0-45,47-91: Terminated
srun: error: x1005c0s5b1n0: tasks 184-205,207-275: Terminated
srun: error: x1005c0s4b0n1: tasks 92-106,108-120,122-183: Terminated
srun: Force Terminated StepId=6017728.0
```

## Expected behavior
I would expect a turbulent but consistent flow from west to east, with x-velocities of around 8m/s.

## AMR-Wind information
```
==============================================================================
                AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: v3.2.0-3-gc7e8abbd
  AMR-Wind Git SHA :: c7e8abbdfbf6674967bc42600ad2b6f4a8446a4c
  AMReX version    :: 24.09-45-g6d9c25b989f1

  Exec. time       :: Sat Nov  9 20:23:54 2024
  Build time       :: Nov  7 2024 11:10:06
  C++ compiler     :: GNU 8.5.0

  MPI              :: ON    (Num. ranks = 736)
  GPU              :: OFF
  OpenMP           :: OFF

  Enabled third-party libraries: 
    NetCDF    4.9.2
    OpenFAST  

           This software is released under the BSD 3-clause license.           
 See https://github.com/Exawind/amr-wind/blob/development/LICENSE for details. 
------------------------------------------------------------------------------
```

## Additional context
Development of the flow: 
Snapshot of flow in x-direction at 500s
![image](https://github.com/user-attachments/assets/169d6e78-317b-45ef-aef3-4b985f4a4017)
600s
![image](https://github.com/user-attachments/assets/1e8a7c70-b9e7-4297-b282-f58194f97829)
700s
![image](https://github.com/user-attachments/assets/12f54eb0-c97c-4c3e-88fc-44fa516cc906)
800s
![image](https://github.com/user-attachments/assets/bea0145d-cdd5-428c-bff6-926f4e4d46d2)
890s -- right before it crashes. Note how the colorbar limits change over time.
![image](https://github.com/user-attachments/assets/0f23919b-2be1-4715-8b98-eef4616b9bd8)

**Comment by mchurchf** [comment] 2024-11-14 18:08
Joeri, what are your north and south BCs?  They should be periodic.  They don't appear to be because the oddness that happens on the north doesn't match what happens on the south.

**Comment by jfrederik-nrel** [comment] 2024-11-14 18:26
Hi Matt, you are right that they are not periodic. I will try running it with periodicity on the y-boundaries and will let you know whether that fixed the problem. 
One argument I would make against this being the reason is that for the initial precursor simulation I encountered this problem in, the inflow direction was 240 degrees, with both xlo and ylo being mass_inflow boundaries.

**Comment by mchurchf** [comment] 2024-11-14 18:30
Can you give details about the original 240 degree case?  240 degrees at hub height?  Any chance there is >30 degree wind direction change from the height of 240 degrees.  What I mean is: is there any chance there is some flow from >270 that might be trying to come in on the north side.

**Comment by jfrederik-nrel** [comment] 2024-11-14 18:49
The original case was set up similarly to this case, bar the direction difference and a bigger flow field (5x5km). See below a couple of snapshots of the flow at hub height from this simulation:

Average wind speed over first 4000s:
![image](https://github.com/user-attachments/assets/76165496-b386-4035-81e1-3b587ff4b004)

Snapshot of wind speed at 4000s:
![image](https://github.com/user-attachments/assets/ff714226-0878-45a9-942d-a0cd25337f18)

Snapshot of wind speed at 5000s:
![image](https://github.com/user-attachments/assets/b5b29cd4-f13c-4a0b-b7a7-5af81f94fb14)

Snapshot of wind speed at 6000s:
![image](https://github.com/user-attachments/assets/aaa333d7-dd71-4127-8fca-42120636eb37)

y-velocity at 6000s: (seems well >0 everywhere)
![image](https://github.com/user-attachments/assets/18719744-81e9-449e-9d31-4aea02f1e635)

Snapshot at 7000s:
![image](https://github.com/user-attachments/assets/362cca6c-e75c-4dc0-9aae-5c5fb26a1d17)

**Comment by mbkuhn** [comment] 2024-11-25 18:38
@jfrederik-nrel Any updates on this issue? Did things work out with a different setup?

**Comment by mbkuhn** [comment] 2024-11-25 18:59
Sounds good. I'm going to add some more details from our Teams conversations, then close the issue, if that's ok.

**Comment by mbkuhn** [comment] 2024-11-25 19:09
Here's my best explanation of what's happened here. Joeri's precursor simulation was very long (at least by Regis's standards), which led to a reversal of the flow at high heights from the Coriolis term. This is stable in the precursor, but it leads to problems in the subsequent inflow-outflow simulations. When this problem first arose, there was a flaw (prior to #1340) in the clipped outflow implementation that left the clipping off. This leads to the straight, inward jets shown in Joeri's plots. PR #1340 corrected this bug regarding the clipping of inward velocities at outflow planes, but the strong flow in the reverse direction remained because it was caused by the Coriolis forcing.

Joeri provided me with the following picture after #1340, which no longer shows those inward jets directly coming from the xhi boundary. However, the strong reverse flow remains.
![image (9)](https://github.com/user-attachments/assets/50b29230-516c-4584-b4a5-231de006247b)

By going back to an earlier time in the precursor, this problem was eliminated. There is potential that this problem could be instead addressed by using mass inflow-outflow conditions, which should allow for inflow and outflow on the same boundary, but that would also require saving boundary planes at those boundaries. As it stands, this strong flow reversal, requiring both inward and outward flow on the same BC plane, is not what the pressure_outflow BC is intended for.

**Closed by mbkuhn** 2024-11-25 19:09 UTC
Labels: bug:amr-wind
